#//////////////////////////////////////////////////////////////////////////////////////
#//////////////////////////  VISTAS Y  TRIGERS      ///////////////////////////////////
#//////////////////////////////////////////////////////////////////////////////////////

CREATE DATABASE HITO_4;
USE HITO_4;

CREATE TABLE USERS(
    ID_USER INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FULLNAME VARCHAR(50) NOT NULL ,
    LASTNAME VARCHAR(50) NOT NULL ,
    AGE INTEGER NOT NULL ,
    EMAIL VARCHAR(100) NOT NULL
);

INSERT INTO USERS(FULLNAME, LASTNAME, AGE, EMAIL)
VALUES('USER1','USERLASTNAME1',20,'USER1@GMAIL.COM'),
      ('USER2','USERLASTNAME2',30,'USER2@GMAIL.COM'),
      ('USER3','USERLASTNAME3',40,'USER3@GMAIL.COM'),
      ('USER4','USERLASTNAME4',50,'USER4@GMAIL.COM'),
      ('USER5','USERLASTNAME5',60,'USER5@GMAIL.COM');


#///////   VISTAS CONCEPTOS   ///////

#VISTA: ES SIMILAR A UNA NUEVA TABLA, (TABLA VIRTUAL) DONDE NO SE NECESITA CREAR LA TABLA, AUNQUE SE TRABAJA COMO UNA
#       NACEN APARTIR DE UNA CONSULTA SQL MEDIANTE LA SINTAXIS " CREATE VIEW ":
#       SE MODIFICA MEDIANTE LA SINTAXIS "ALTER VIEW NOMBRE_VISTA"
#       SE ELIMINA MEDIANTE LA SINTAXIS "DROPE VIEW NOMBRE_DE_LA_VISTA"

CREATE OR REPLACE VIEW MAYORES_A_40 AS
SELECT USERS.FULLNAME AS NOMBRE_PERSONA,
       USERS.LASTNAME AS APELLLIDO_PERSONA,
       USERS.AGE AS EDAD_PERSONA

FROM  USERS
WHERE AGE >40;

SELECT*
FROM MAYORES_A_40
WHERE EDAD_PERSONA > 40;

DROP VIEW MAYORES_A_40;

#CREANDO NUEVO REGISTRO PARA COMPROBAR SI LA VISTA MUESTRA EL REGISTRO

INSERT INTO USERS(FULLNAME, LASTNAME, AGE, EMAIL)
VALUES('USER6','USERLASTNAME6',70,'USER6@GMAIL.COM');


#/////   TRIGERS CONCEPTOS  ///

# SE EJECUTA DE MANERA AUTOMATICA
# CUANDO SE EJECUTA? CUANDO OCUYRRE LOS SIGUIENTES EVENTOS : INSERT, UPDATE O DELETE
# ES DECIR, CADA VEZ QUE INSERTO, MODIFICO O ELIMINO EL REGISTRO DE UNA TABLA
# POR CONSIGUIENTE UN TRIGGER SIEMPRE SE APLICA A UNA TABLA

# UN TRIGGER PUEDE ACCEDER A TODOS LOS CAMPOS DE UNA TABLA
# Y LO HACE ATRAVES DE LOS OBJETOS NEW Y OLD
# NEW = INSERT
# OLD = DELETE
# NEW Y OLD = UPDATE

ALTER TABLE USERS ADD COLUMN PASSWORD VARCHAR(50);

CREATE OR REPLACE TRIGGER GENERAR_PASSWORD
    BEFORE INSERT ON USERS
    FOR EACH ROW
    BEGIN
        SET NEW.PASSWORD=CONCAT(SUBSTRING(NEW.FULLNAME,1,2),SUBSTRING(NEW.LASTNAME,1,2),NEW.AGE);
    END;

INSERT INTO USERS(FULLNAME, LASTNAME, AGE, EMAIL)
VALUES('USER8','USERLASTNAME8',90,'USER8@GMAIL.COM');

SELECT* FROM USERS;

#///////////////////////////////////////////////////////////////////////////////////////
#////////////////       EJERCICIO  1    ////////////////////////////////////////////////
#///////////////////////////////////////////////////////////////////////////////////////

CREATE TABLE NUMEROS (
    NUMERO BIGINT PRIMARY KEY NOT NULL ,
    CUADRADO BIGINT,
    CUBO BIGINT,
    RAIZCUADRADA REAL
);

#///////         TRIGGER      ////////////

CREATE OR REPLACE TRIGGER OP_MATEMATICAS
    BEFORE INSERT ON NUMEROS
    FOR EACH ROW
    BEGIN
       SET NEW.CUADRADO=NEW.NUMERO*NEW.NUMERO;
       SET NEW.CUBO=POW(NEW.NUMERO,3);
       SET NEW.RAIZCUADRADA=SQRT(NEW.NUMERO);
    END;

INSERT INTO NUMEROS (NUMERO)VALUES (3);

SELECT * FROM NUMEROS;